language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database crt;' -U postgres
  - psql -c 'create database testdb;' -U postgres

script:
  - python -m unittest tests